### ISSUE TITLE
Fix cooldown manager  // Move commands to own configuration // cooldown config

### ISSUE THREAD

**Issue by Antritus** [AstralLiteratureClub/Fluffy#2]
Fix issues with the cooldown manager. Items like chorus fruit need their own class like ender pearl one has to do the cooldown after the default minecraft cooldown. Minecraft for some reason overrides cooldowns.

Add cooldowns for commands when in combat to make them no longer spammed. Commands could get global cooldown or a command specific cooldown

Improve configurations of the cooldowns and add command cooldowns 

item-cooldowns.yml
```yaml
ENCHANTED_GOLDEN_APPLE:
  cooldown: 500 # ticks

ENDER_PEARL:
  cooldown: 350
  allow-bypass: # fluffy-.combat.item.ender_pearl.allow-bypass

GOLDEN_APPLE:
  cooldown: 100
```

command.yml
```yaml
teleport:
  cooldown: 600

tp:
  cooldown: 600 
  allow-bypass: true #bypass fluffy-.combat.command.spawn.-allow-cooldown-bypass

spawn:
  disabled: true
  allow-bypass: true #bypass permission: fluffy-.combat.command.spawn.allow-bypass
```
